#!/bin/sh
python /opt/FlaskServer/DB_Creation.py $MYSQL_HOST $MYSQL_USER $MYSQL_PASSWORD $MYSQL_PORT $MYSQL_DB_NAME $MYSQL_TABLE_NAME $SERVICE_KEYS
python /opt/FlaskServer/Flask_Mysql_Server.py $MYSQL_HOST $MYSQL_USER $MYSQL_PASSWORD $MYSQL_PORT $MYSQL_DB_NAME $MYSQL_TABLE_NAME $SERVICE_KEYS
